
package com.mycompany.cine.Vistas;

import com.mycompany.cine.Vistas.VCliente;
import com.mycompany.cine.Vistas.VPelicula;
import com.mycompany.cine.Vistas.VSalas;
import com.mycompany.cine.sala.Salas;
import com.mycompany.cine.pelicula.Peliculas;
import com.mycompany.cine.Controladores.*;
import com.mycompany.cine.Imagenes.FondoPanel;



public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    private VCliente ventanaC;
    private VSalas ventanaS;
    private VPelicula ventanaP;
    private VPeliculaSala ventanaPS;
    private Salas salas;
    private Peliculas peliculas;

    /**
     * Creates new form VistaPrincipal
     */
    
    FondoPanel fondo = new FondoPanel();

    public VistaPrincipal() {
        this.setContentPane(fondo); 
        initComponents();
        setLocationRelativeTo(null);

    salas = new Salas();
    peliculas = new Peliculas();

    ventanaS = new VSalas();
    ventanaP = new VPelicula();
    ventanaPS = new VPeliculaSala();

    ControladorSalas cSalas =
            new ControladorSalas(ventanaS, salas);

    ControladorPeliculas cPeliculas =
            new ControladorPeliculas(ventanaP, peliculas);

    ControladorPeliculaSala cPS =
            new ControladorPeliculaSala(ventanaPS, salas, peliculas);

    ventanaS.setControlador(cSalas);
    ventanaP.setControlador(cPeliculas);
    ventanaPS.setControlador(cPS);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnCliente = new javax.swing.JButton();
        btnSalas = new javax.swing.JButton();
        btnPelicula = new javax.swing.JButton();
        btnPeliculasSalas = new javax.swing.JButton();
        btnReservarAsientos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnSalas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalas.setText("Salas");
        btnSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasActionPerformed(evt);
            }
        });

        btnPelicula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPelicula.setText("Peliculas");
        btnPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculaActionPerformed(evt);
            }
        });

        btnPeliculasSalas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPeliculasSalas.setText("Peliculas asignada en Salas");
        btnPeliculasSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasSalasActionPerformed(evt);
            }
        });

        btnReservarAsientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReservarAsientos.setText("Reservar Asientos");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        btnCerrar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnReservarAsientos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnPeliculasSalas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCliente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSalas)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSalas)
                .addGap(28, 28, 28)
                .addComponent(btnPelicula)
                .addGap(26, 26, 26)
                .addComponent(btnPeliculasSalas)
                .addGap(26, 26, 26)
                .addComponent(btnReservarAsientos)
                .addGap(27, 27, 27)
                .addComponent(btnCerrar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        if (ventanaC == null) {
            ventanaC = new VCliente();
        }
        ventanaC.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasActionPerformed
        if (ventanaS == null) {
            ventanaS = new VSalas();
        }
        ventanaS.setVisible(true);
   
    }//GEN-LAST:event_btnSalasActionPerformed

    private void btnPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculaActionPerformed
        if (ventanaP == null) {
            ventanaP = new VPelicula();
        }
        ventanaP.setVisible(true); // Mostrar la ventana correctamente }      // TODO add your handling code here:
    }//GEN-LAST:event_btnPeliculaActionPerformed

    private void btnPeliculasSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasSalasActionPerformed
         if (ventanaPS == null) {
        ventanaPS = new VPeliculaSala();
        }
        ventanaPS.setVisible(true);         // TODO add your handling code here:
          // TODO add your handling code here:
    }//GEN-LAST:event_btnPeliculasSalasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnPelicula;
    private javax.swing.JButton btnPeliculasSalas;
    private javax.swing.JButton btnReservarAsientos;
    private javax.swing.JButton btnSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
